services:
  - type: web
    name: avangarda-cms
    runtime: node
    plan: free
    rootDir: apps/cms
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 1337
      - key: PUBLIC_URL
        sync: false
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: postgres
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_SSL
        value: true
      - key: CLOUDINARY_NAME
        value: avangarda-media
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
