import type { Lang } from "@/lib/i18n";

export const SUPPORT_RECIPIENT = "Udruženje „NOVA SPONA – Centar za društvene inicijative“";
export const SUPPORT_BANK = "Banka Poštanska štedionica";
export const SUPPORT_ACCOUNT = "200-0810000016001-58";
export const SUPPORT_PURPOSE = "Dobrovoljni prilog za projekat Avangarda";
export const SUPPORT_EMAIL = "info@avangarda.media";

export type SupportPageCopy = {
  eyebrow: string;
  title: string;
  intro: string;
  paymentTitle: string;
  recipientLabel: string;
  bankLabel: string;
  accountLabel: string;
  purposeLabel: string;
  paymentCodeLabel: string;
  electronicCode: string;
  cashCode: string;
  modelLabel: string;
  modelValue: string;
  amountLabel: string;
  amountValue: string;
  copyAccount: string;
  accountCopied: string;
  copyPurpose: string;
  purposeCopied: string;
  copyFailed: string;
  explanationTitle: string;
  explanation: string;
  contactTitle: string;
  contactText: string;
};

export const supportPageCopy: Record<Lang, SupportPageCopy> = {
  sr: {
    eyebrow: "PODRŠKA",
    title: "Podrži nezavisan rad",
    intro: "Avangarda je nezavisna autorska i informativna platforma NOVE SPONE. Podrška pomaže nastanak novih priča, terenski rad, prevode i održavanje platforme.",
    paymentTitle: "Podaci za uplatu",
    recipientLabel: "Primalac",
    bankLabel: "Banka",
    accountLabel: "Broj računa",
    purposeLabel: "Svrha uplate",
    paymentCodeLabel: "Šifra plaćanja",
    electronicCode: "za elektronsku ili drugu bezgotovinsku uplatu fizičkog lica",
    cashCode: "za gotovinsku uplatu na šalteru",
    modelLabel: "Model i poziv na broj",
    modelValue: "Nisu potrebni i ostavljaju se prazni.",
    amountLabel: "Iznos",
    amountValue: "Po izboru",
    copyAccount: "Kopiraj broj računa",
    accountCopied: "Broj računa je kopiran",
    copyPurpose: "Kopiraj svrhu uplate",
    purposeCopied: "Svrha uplate je kopirana",
    copyFailed: "Kopiranje nije uspelo",
    explanationTitle: "Kako se podrška evidentira",
    explanation: "Sredstva prima NOVA SPONA kao pravno lice i evidentiraju se kroz knjigovodstvo udruženja za podršku projektu Avangarda.",
    contactTitle: "Pravna lica i podrška iz inostranstva",
    contactText: "Pravna lica i osobe koje žele da podrže projekat iz inostranstva mogu da nam se jave na",
  },
  en: {
    eyebrow: "SUPPORT",
    title: "Support independent work",
    intro: "Avangarda is an independent author-led and information platform of NOVA SPONA. Support helps fund new stories, field reporting, translations and platform maintenance.",
    paymentTitle: "Payment details",
    recipientLabel: "Recipient",
    bankLabel: "Bank",
    accountLabel: "Account number",
    purposeLabel: "Payment purpose",
    paymentCodeLabel: "Payment code",
    electronicCode: "for an electronic or other cashless payment by an individual",
    cashCode: "for a cash payment at a bank counter",
    modelLabel: "Model and reference number",
    modelValue: "They are not required and should be left blank.",
    amountLabel: "Amount",
    amountValue: "Your choice",
    copyAccount: "Copy account number",
    accountCopied: "Account number copied",
    copyPurpose: "Copy payment purpose",
    purposeCopied: "Payment purpose copied",
    copyFailed: "Copying failed",
    explanationTitle: "How support is recorded",
    explanation: "NOVA SPONA receives the funds as a legal entity, and the association records them in its accounts as support for the Avangarda project.",
    contactTitle: "Legal entities and international support",
    contactText: "Legal entities and people who wish to support the project from abroad can contact us at",
  },
  tr: {
    eyebrow: "DESTEK",
    title: "Bağımsız çalışmayı destekleyin",
    intro: "Avangarda, NOVA SPONA'nın bağımsız yazar ve haber platformudur. Destek; yeni hikâyelerin, saha çalışmalarının, çevirilerin ve platform bakımının sürdürülmesine yardımcı olur.",
    paymentTitle: "Ödeme bilgileri",
    recipientLabel: "Alıcı",
    bankLabel: "Banka",
    accountLabel: "Hesap numarası",
    purposeLabel: "Ödeme amacı",
    paymentCodeLabel: "Ödeme kodu",
    electronicCode: "gerçek kişinin elektronik veya diğer nakitsiz ödemesi için",
    cashCode: "gişeden nakit ödeme için",
    modelLabel: "Model ve referans numarası",
    modelValue: "Gerekli değildir ve boş bırakılmalıdır.",
    amountLabel: "Tutar",
    amountValue: "Sizin seçiminiz",
    copyAccount: "Hesap numarasını kopyala",
    accountCopied: "Hesap numarası kopyalandı",
    copyPurpose: "Ödeme amacını kopyala",
    purposeCopied: "Ödeme amacı kopyalandı",
    copyFailed: "Kopyalama başarısız oldu",
    explanationTitle: "Destek nasıl kaydedilir",
    explanation: "Fonları tüzel kişi olarak NOVA SPONA alır ve derneğin muhasebesinde Avangarda projesine destek olarak kaydeder.",
    contactTitle: "Tüzel kişiler ve yurt dışından destek",
    contactText: "Tüzel kişiler ve projeyi yurt dışından desteklemek isteyenler bize şu adresten ulaşabilir",
  },
  de: {
    eyebrow: "UNTERSTÜTZUNG",
    title: "Unabhängige Arbeit unterstützen",
    intro: "Avangarda ist die unabhängige Autoren- und Informationsplattform von NOVA SPONA. Unterstützung ermöglicht neue Geschichten, Recherchen vor Ort, Übersetzungen und den Betrieb der Plattform.",
    paymentTitle: "Zahlungsdaten",
    recipientLabel: "Empfänger",
    bankLabel: "Bank",
    accountLabel: "Kontonummer",
    purposeLabel: "Verwendungszweck",
    paymentCodeLabel: "Zahlungscode",
    electronicCode: "für eine elektronische oder andere bargeldlose Zahlung einer Privatperson",
    cashCode: "für eine Bareinzahlung am Schalter",
    modelLabel: "Modell und Referenznummer",
    modelValue: "Sie sind nicht erforderlich und bleiben leer.",
    amountLabel: "Betrag",
    amountValue: "Nach eigener Wahl",
    copyAccount: "Kontonummer kopieren",
    accountCopied: "Kontonummer kopiert",
    copyPurpose: "Verwendungszweck kopieren",
    purposeCopied: "Verwendungszweck kopiert",
    copyFailed: "Kopieren fehlgeschlagen",
    explanationTitle: "Wie die Unterstützung verbucht wird",
    explanation: "NOVA SPONA nimmt die Mittel als juristische Person entgegen und verbucht sie über die Buchhaltung des Vereins als Unterstützung für das Projekt Avangarda.",
    contactTitle: "Juristische Personen und Unterstützung aus dem Ausland",
    contactText: "Juristische Personen und Personen, die das Projekt aus dem Ausland unterstützen möchten, erreichen uns unter",
  },
  fr: {
    eyebrow: "SOUTIEN",
    title: "Soutenir un travail indépendant",
    intro: "Avangarda est la plateforme indépendante d'auteurs et d'information de NOVA SPONA. Le soutien contribue à de nouveaux récits, au travail de terrain, aux traductions et à la maintenance de la plateforme.",
    paymentTitle: "Données de paiement",
    recipientLabel: "Bénéficiaire",
    bankLabel: "Banque",
    accountLabel: "Numéro de compte",
    purposeLabel: "Objet du paiement",
    paymentCodeLabel: "Code de paiement",
    electronicCode: "pour un paiement électronique ou autre paiement sans espèces d'une personne physique",
    cashCode: "pour un paiement en espèces au guichet",
    modelLabel: "Modèle et numéro de référence",
    modelValue: "Ils ne sont pas requis et doivent rester vides.",
    amountLabel: "Montant",
    amountValue: "Au choix",
    copyAccount: "Copier le numéro de compte",
    accountCopied: "Numéro de compte copié",
    copyPurpose: "Copier l'objet du paiement",
    purposeCopied: "Objet du paiement copié",
    copyFailed: "La copie a échoué",
    explanationTitle: "Comment le soutien est comptabilisé",
    explanation: "NOVA SPONA reçoit les fonds en tant que personne morale et l'association les comptabilise comme soutien au projet Avangarda.",
    contactTitle: "Personnes morales et soutien depuis l'étranger",
    contactText: "Les personnes morales et celles qui souhaitent soutenir le projet depuis l'étranger peuvent nous écrire à",
  },
  es: {
    eyebrow: "APOYO",
    title: "Apoya el trabajo independiente",
    intro: "Avangarda es la plataforma independiente de autoría e información de NOVA SPONA. El apoyo contribuye a nuevas historias, trabajo de campo, traducciones y mantenimiento de la plataforma.",
    paymentTitle: "Datos de pago",
    recipientLabel: "Beneficiario",
    bankLabel: "Banco",
    accountLabel: "Número de cuenta",
    purposeLabel: "Concepto del pago",
    paymentCodeLabel: "Código de pago",
    electronicCode: "para un pago electrónico u otro pago sin efectivo de una persona física",
    cashCode: "para un pago en efectivo en ventanilla",
    modelLabel: "Modelo y número de referencia",
    modelValue: "No son necesarios y deben dejarse en blanco.",
    amountLabel: "Importe",
    amountValue: "A elección",
    copyAccount: "Copiar número de cuenta",
    accountCopied: "Número de cuenta copiado",
    copyPurpose: "Copiar concepto del pago",
    purposeCopied: "Concepto del pago copiado",
    copyFailed: "No se pudo copiar",
    explanationTitle: "Cómo se registra el apoyo",
    explanation: "NOVA SPONA recibe los fondos como persona jurídica y la asociación los registra en su contabilidad como apoyo al proyecto Avangarda.",
    contactTitle: "Personas jurídicas y apoyo desde el extranjero",
    contactText: "Las personas jurídicas y quienes quieran apoyar el proyecto desde el extranjero pueden escribirnos a",
  },
  el: {
    eyebrow: "ΣΤΗΡΙΞΗ",
    title: "Στήριξε την ανεξάρτητη εργασία",
    intro: "Η Avangarda είναι η ανεξάρτητη συγγραφική και ενημερωτική πλατφόρμα της NOVA SPONA. Η στήριξη συμβάλλει σε νέες ιστορίες, επιτόπια έρευνα, μεταφράσεις και συντήρηση της πλατφόρμας.",
    paymentTitle: "Στοιχεία πληρωμής",
    recipientLabel: "Δικαιούχος",
    bankLabel: "Τράπεζα",
    accountLabel: "Αριθμός λογαριασμού",
    purposeLabel: "Αιτιολογία πληρωμής",
    paymentCodeLabel: "Κωδικός πληρωμής",
    electronicCode: "για ηλεκτρονική ή άλλη πληρωμή χωρίς μετρητά από φυσικό πρόσωπο",
    cashCode: "για πληρωμή με μετρητά στο ταμείο",
    modelLabel: "Μοντέλο και αριθμός αναφοράς",
    modelValue: "Δεν απαιτούνται και παραμένουν κενά.",
    amountLabel: "Ποσό",
    amountValue: "Κατά επιλογή",
    copyAccount: "Αντιγραφή αριθμού λογαριασμού",
    accountCopied: "Ο αριθμός λογαριασμού αντιγράφηκε",
    copyPurpose: "Αντιγραφή αιτιολογίας",
    purposeCopied: "Η αιτιολογία αντιγράφηκε",
    copyFailed: "Η αντιγραφή απέτυχε",
    explanationTitle: "Πώς καταγράφεται η στήριξη",
    explanation: "Η NOVA SPONA λαμβάνει τα χρήματα ως νομικό πρόσωπο και ο σύλλογος τα καταγράφει λογιστικά ως στήριξη του έργου Avangarda.",
    contactTitle: "Νομικά πρόσωπα και στήριξη από το εξωτερικό",
    contactText: "Νομικά πρόσωπα και όσοι θέλουν να στηρίξουν το έργο από το εξωτερικό μπορούν να επικοινωνήσουν μαζί μας στο",
  },
  ar: {
    eyebrow: "الدعم",
    title: "ادعم العمل المستقل",
    intro: "أفانغاردا منصة مستقلة للمؤلفين والمعلومات تابعة لـ NOVA SPONA. يساهم الدعم في إنتاج قصص جديدة والعمل الميداني والترجمات وصيانة المنصة.",
    paymentTitle: "بيانات الدفع",
    recipientLabel: "المستفيد",
    bankLabel: "البنك",
    accountLabel: "رقم الحساب",
    purposeLabel: "غرض الدفع",
    paymentCodeLabel: "رمز الدفع",
    electronicCode: "للدفع الإلكتروني أو أي دفع آخر غير نقدي من شخص طبيعي",
    cashCode: "للدفع النقدي عند الشباك",
    modelLabel: "النموذج والرقم المرجعي",
    modelValue: "غير مطلوبين ويُتركان فارغين.",
    amountLabel: "المبلغ",
    amountValue: "حسب اختيارك",
    copyAccount: "نسخ رقم الحساب",
    accountCopied: "تم نسخ رقم الحساب",
    copyPurpose: "نسخ غرض الدفع",
    purposeCopied: "تم نسخ غرض الدفع",
    copyFailed: "تعذر النسخ",
    explanationTitle: "كيف يُسجل الدعم",
    explanation: "تتلقى NOVA SPONA الأموال بصفتها شخصًا اعتباريًا، وتُسجلها الجمعية في حساباتها دعمًا لمشروع Avangarda.",
    contactTitle: "الأشخاص الاعتباريون والدعم من الخارج",
    contactText: "يمكن للأشخاص الاعتباريين ولمن يرغبون في دعم المشروع من الخارج التواصل معنا عبر",
  },
};
